# Database settings.
database:

  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: 123eRTy789!)

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/IVManager
  
cacheBuilderSpec: maximumSize=10000, expireAfterAccess=10m